-- Simple CDC pattern using a Stream and a Task.
-- The Stream records changes. The Task processes those changes.

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_CURATED (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE STREAM CUSTOMER_RAW_STREAM
ON TABLE CUSTOMER_RAW;

-- Add a new customer or update an existing row.
INSERT INTO CUSTOMER_RAW (CUSTOMER_ID, CUSTOMER_NAME, EMAIL)
VALUES (1, 'John Doe', 'john@example.com');

-- The Task can read only the changes captured by the Stream.
CREATE OR REPLACE TASK PROCESS_CUSTOMER_CHANGES
  WAREHOUSE = WH_DEV
  SCHEDULE = '5 MINUTE'
AS
MERGE INTO CUSTOMER_CURATED target
USING (
    SELECT CUSTOMER_ID, CUSTOMER_NAME, EMAIL, UPDATED_AT
    FROM CUSTOMER_RAW_STREAM
    WHERE METADATA$ACTION = 'INSERT'
) source
ON target.CUSTOMER_ID = source.CUSTOMER_ID
WHEN MATCHED THEN UPDATE SET
    CUSTOMER_NAME = source.CUSTOMER_NAME,
    EMAIL = source.EMAIL,
    UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED THEN INSERT
    (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, UPDATED_AT)
VALUES
    (source.CUSTOMER_ID, source.CUSTOMER_NAME, source.EMAIL, source.UPDATED_AT);

-- Enable the Task when the required warehouse and objects are ready.
-- ALTER TASK PROCESS_CUSTOMER_CHANGES RESUME;
