-- Basic Snowflake setup
-- Keep databases and schemas organized by environment and purpose.

CREATE DATABASE IF NOT EXISTS DB_DEV;

CREATE SCHEMA IF NOT EXISTS DB_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS DB_DEV.CURATED;

CREATE OR REPLACE WAREHOUSE WH_DEV
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE DATABASE DB_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    CREATED_DATE DATE
);

-- Check the setup
SHOW DATABASES;
SHOW SCHEMAS;
SHOW WAREHOUSES;
